### ISSUE TITLE
Keep Routes.agencyId

### ISSUE THREAD

**Issue by mhnagaoka** [raeffray/vantransitDigest#2]
This allows creating Agency -[OPERATES]-> Routes with a single Cypher statement:

```
match (a:Agency),(r:Routes) where a.agencyId = r.agencyId create a-[rl:OPERATES]->r return rl
```

@raeffray what do you think?

**Comment by raeffray** [comment]
For me it's OK. We can keep, for sure. The only thing is that, based in my recent experience, making joins and then creating the relationship it's not a good option when you have some thousands of nodes. That was my first choice: flush everything into neo4j and then make some queries in order to create the relationships. My world fell apart when I had to join Route and Trip. The performance was terrible, taking some minutes to retrieve one route and its trips.

**Comment by mhnagaoka** [comment]
You're right. I gave up running `match (t:Trips),(st:StopTimes) where t.tripId = st.tripId create t-[rl:STOPS_AT]->st return rl`. Even after creating indexes with `create index on :Trips(tripId)` and `create index on :StopTimes(tripId)`, the command above didn't complete after a *whole night* crunching the CPU!

The problem now is to keep track of each node id or [batch job id](http://neo4j.com/docs/stable/rest-api-batch-ops.html#rest-api-refer-to-items-created-earlier-in-the-same-batch-job) to further create the relationships. Note that in `BatchLoader` I tried to avoid keeping a lot of objects (`RawData`) created from the CSV files in memory.

**Comment by mhnagaoka** [comment]
Just for posterity, these are the Cypher commands I used for creating the relationships:

```
match (a:Agency),(r:Routes) where a.agencyId = r.agencyId create a-[rl:OPERATES]->r return rl
match (r:Routes),(t:Trips) where r.routeId = t.routeId create r-[rl:TRAVELS]->t return rl
create index on :Trips(tripId)
create index on :StopTimes(tripId)
match (t:Trips),(st:StopTimes) where t.tripId = st.tripId create t-[rl:STOPS_AT]->st return rl
```
